name: Docker

on:
  push:
    branches:
      - 'imager'

jobs:
  manager:
    name: Deploy manager Image
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3.4.0
      - name: Publish Docker Image
        uses: openzim/docker-publish-action@v10
        with:
          image-name: offspot/cardshop-manager
          on-master: imager
          restrict-to: offspot/cardshop
          context: manager
          registries: ghcr.io
          credentials:
            GHCRIO_USERNAME=${{ secrets.GHCR_USERNAME }}
            GHCRIO_TOKEN=${{ secrets.GHCR_TOKEN }}
